spam_detector/message_app/urls.py
from .views import inbox, individual_message, new_message
from django.urls import path

app_name = 'messages'

urlpatterns = [
    path('inbox', inbox, name='inbox'),
    path('read/<int:pk>/', individual_message, name='read'),
    path('new', new_message, name='new'),
]

spam_detector/spam_detector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('messages/', include('message_app.urls'))
]

spam_detector/message_app/models.py
from django.db import models
import pickle
import numpy as np 
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence  import pad_sequences
from tensorflow.keras.models import load_model


# Create your models here.
from django.utils import timezone

SEQUENCE_LENGTH=100



class Message(models.Model):
    sender = models.CharField(max_length=255)
    recipient = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    content = models.TextField()
    when_sent = models.DateTimeField(null=False, blank=False, default=timezone.now)
    read = models.BooleanField(default=False)
    spam_detected = models.BooleanField(default=False)

    def do_analysis(self, text):
        tokenizer=Tokenizer()
        int_label={0:'ham',1:'spam'}
        model=load_model('model.h5')
        sequence = tokenizer.texts_to_sequences([text]) 
        # pad the sequence
        sequence = pad_sequences(sequence, maxlen=SEQUENCE_LENGTH)
        # get the prediction
        prediction = model.predict(sequence)[0]
        # one-hot encoded vector, revert using np.argmax
        return int_label[np.argmax(prediction)]

    def get_predictions(self,  ):
        res = self.do_analysis(self.content)
        if res == 'spam':
            self.spam_detected = True
        self.save( )

spam_detector/message_app/forms.py
from django import forms


class NewMessageForm(forms.Form):
    recipient = forms.CharField(label='Recipient name', max_length=100)
    content = forms.CharField(label='Content info', max_length=100)
    subject = forms.CharField(label='subject', max_length=100)

spam_detector/message_app/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Q

from .forms import NewMessageForm
from .models import Message

# Create your views here.
@login_required
def inbox(request, *args, **kwargs):
    logged_in_user = request.user.username
    messages = Message.objects.filter(Q(sender__iexact=logged_in_user)|Q(recipient__iexact=login_required()))
    context = {
        'inboxes': messages
    }
    return render(request, 'messages_app/inbox.html', context=context)


@login_required
def individual_message(request, *args, **kwargs):
    message_id = kwargs['pk']
    message = Message.objects.get(pk=message_id)
    message.read = True
    message.save()
    message.get_predictions()
    return render(request, 'messages_app/read.html', {'message':message})


@login_required
def new_message(request):
    if request.method == 'POST':
        form = NewMessageForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            sender = request.user.username
            recipient = form.cleaned_data['recipient']
            content = form.cleaned_data['content']
            subject = form.cleaned_data['subject']
            Message.objects.create(sender=sender, recipient=recipient, subject=subject, content=content)
            return HttpResponseRedirect('/messages/inbox')
    else:
        form = NewMessageForm()
    return render(request, 'messages_app/new_message.html', {'form': form})

spam_detector/message_app/templates/messages_app/inbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inbox</title>
</head>
<body>
My messages

<table>
    <tr>
        <th>Subject</th>
        <th>From</th>
        <th>To</th>
        <th>Spam</th>
    </tr>
    {% for message in inboxes %}
    <tr>
        <td><a href="{% url 'messages:read' message.id  %}"> {{message.subject}} </a> </td>
        <td>{{message.sender}}</td>
        <td>{{message.recipient}}</td>
        <td>{{message.spam_detected</td>

    </tr>
    {% endfor %}
</table>
 <a href="{% url 'messages:new' %}"><button>New Message</button></a>
</body>
</html>

spam_detector/message_app/templates/messages_app/new_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NEW Message</title>
</head>
<body>
{{form.errors}}
  <form method="POST" action="">
      {% csrf_token %}
    {{form.as_p}}
      <input type="submit" value="Send">
  </form>
</body>
</html>

spam_detector/message_app/templates/messages_app/read.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Read Message</title>
</head>
<body>
  <h2>New message</h2>
  <h3>Subject : {{message.subject}}</h3>
  <h4>From : {{message.sender}}</h4>

  <p>{{message.content}}</p>

    <a href="{% url 'messages:inbox' %}"><button>Back to inbox</button></a>
</body>
</html>